<?php
include_once '../Auto.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-10 at 20:04:44.
 */
class AutoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Auto
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Auto;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    

    /**
     * @covers Auto::beschleunigen
     * @todo   Implement testBeschleunigen().
     */
    public function testBeschleunigen() {
        $x = $this->object->beschleunigen(2);
        $this->assertEquals($x, 3);
    }

    /**
     * @covers Auto::bremsen
     * @todo   Implement testBremsen().
     */
    public function testBremsen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auto::umlackieren
     * @todo   Implement testUmlackieren().
     */
    public function testUmlackieren() {
        $x = $this->object->umlackieren('rot');
        $this->assertFalse($x);
    }

    /**
     * @covers Auto::getPs
     * @todo   Implement testGetPs().
     */
    public function testGetPs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auto::getFarbe
     * @todo   Implement testGetFarbe().
     */
    public function testGetFarbe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auto::getTyp
     * @todo   Implement testGetTyp().
     */
    public function testGetTyp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auto::getKmh
     * @todo   Implement testGetKmh().
     */
    public function testGetKmh() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auto::setPs
     * @todo   Implement testSetPs().
     */
    public function testSetPs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auto::setFarbe
     * @todo   Implement testSetFarbe().
     */
    public function testSetFarbe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auto::setTyp
     * @todo   Implement testSetTyp().
     */
    public function testSetTyp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auto::setKmh
     * @todo   Implement testSetKmh().
     */
    public function testSetKmh() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
