<?php
include_once '../Calculator.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-10 at 19:09:43.
 */
class CalculatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Calculator::add
     * @dataProvider addProvider
     */
    public function testAdd($z1, $z2, $result) {
        $x = $this->object->add($z1, $z2);
        $this->assertEquals($x, $result);
    }
    
    public function addProvider()
    {
        return array(
            array(1, 2, 3),
            array(0, 0, 0),
            array(-1, 0, -1)
        );
    }

    /**
     * @covers Calculator::multiply
     * @dataProvider multiplyProvider
     */
    public function testMultiply($z1, $z2, $result) {
        $x = $this->object->multiply($z1, $z2);
        $this->assertEquals($x, $result);
    }
    
    public function multiplyProvider()
    {
        return array(
            array(2, 2, 4),
            array(3, 3, 9),
            array(4, 4, 16),
            array(NULL, NULL, NULL)
        );
    }

    /**
     * @covers Calculator::getZahl1
     * @todo   Implement testGetZahl1().
     */
    public function testGetZahl1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Calculator::getZahl2
     * @todo   Implement testGetZahl2().
     */
    public function testGetZahl2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Calculator::setZahl1
     * @todo   Implement testSetZahl1().
     */
    public function testSetZahl1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Calculator::setZahl2
     * @todo   Implement testSetZahl2().
     */
    public function testSetZahl2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
